### ISSUE TITLE
Segfault with Python

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLinearAlgebra/MKL.jl#97]
I've run into similar issues in the past, feel free to close if that's known. When PyCalling into a package (pyscf), it segfaults (with nothing more informative, presumably when pyscf attempts to do linear algebra). I can provide more information if needed, but really it seems that it's just `using MKL; using PyCall; do_something_with_linalg_from_python()`.

**Comment by antoine-levitt** [comment]
I was able to get a stacktrace:
```
signal (11): Segmentation fault
in expression starting at /home/antoine/Dropbox/recherche/2021-06-GTO/test.jl:19
mkl_lapack_ps_avx2_xdlange at /home/antoine/.julia/artifacts/72d4adc3ef9236a92f4fefeb0291cb6e8aaae2d7/lib/libmkl_avx2.so.1 (unknown line)
mkl_lapack_dlange at /home/antoine/.julia/artifacts/72d4adc3ef9236a92f4fefeb0291cb6e8aaae2d7/lib/libmkl_intel_thread.so.1 (unknown line)
dlange_ at /home/antoine/.julia/artifacts/72d4adc3ef9236a92f4fefeb0291cb6e8aaae2d7/lib/libmkl_intel_ilp64.so.1 (unknown line)
unknown function (ip: 0x7fd23b1f6d79)
unknown function (ip: 0x7fd23b149b97)
_PyObject_MakeTpCall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e7347df2)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e7347d6c)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e7347d6c)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e735306a)
unknown function (ip: 0x7fd1e7347d6c)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e7347d6c)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e7347d6c)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e7347d6c)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
PyVectorcall_Call at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e757be0a)
PyVectorcall_Call at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalFrameDefault at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyEval_EvalCodeWithName at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
_PyFunction_Vectorcall at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
unknown function (ip: 0x7fd1e757be0a)
PyVectorcall_Call at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (unknown line)
macro expansion at /home/antoine/.julia/packages/PyCall/3fwVL/src/exception.jl:95 [inlined]
#107 at /home/antoine/.julia/packages/PyCall/3fwVL/src/pyfncall.jl:43 [inlined]
disable_sigint at ./c.jl:458 [inlined]
__pycall! at /home/antoine/.julia/packages/PyCall/3fwVL/src/pyfncall.jl:42 [inlined]
_pycall! at /home/antoine/.julia/packages/PyCall/3fwVL/src/pyfncall.jl:29
_pycall! at /home/antoine/.julia/packages/PyCall/3fwVL/src/pyfncall.jl:11 [inlined]
#_#114 at /home/antoine/.julia/packages/PyCall/3fwVL/src/pyfncall.jl:86 [inlined]
PyObject at /home/antoine/.julia/packages/PyCall/3fwVL/src/pyfncall.jl:86
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:126
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:215
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:166 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:587
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:731
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:885
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:830
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:944
eval at ./boot.jl:373 [inlined]
include_string at ./loading.jl:1196
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
_include at ./loading.jl:1253
include at ./Base.jl:418
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
exec_options at ./client.jl:292
_start at ./client.jl:495
jfptr__start_43127.clone_1 at /home/antoine/julia/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:559
jl_repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:701
main at /buildworker/worker/package_linux64/build/cli/loader_exe.c:42
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/antoine/julia/bin/julia (unknown line)
Allocations: 646536 (Pool: 646118; Big: 418); GC: 1
Segmentation fault (core dumped)
```
Reproducer: install pyscf in python 
```
using MKL
using PyCall

pyscf = pyimport("pyscf")
basis_label = "ccpvtz"
elems = ("H", "O")
atoms = "O 0 0 0; H 0 -2.757 2.587; H 0 2.757 2.587" # H2O

method = pyscf.scf.RHF
mol = pyscf.gto.M(atom = atoms, basis = basis_label)
rhf = method(mol)
rhf.kernel()
```
I've verified this under julia 1.7 (linux), with both my system-provided python and julia's one

**Comment by ViralBShah** [comment]
@staticfloat I thought these issues would be behind us with LBT.

**Comment by jishnub** [comment]
I encounter something similar using `PyPlot`. Loading MKL before `PyPlot` leads to segfaults, while loading `MKL` later works.

This works:
```julia
julia> using PyPlot
         
julia> using MKL

julia> plot(3:4)
1-element Vector{PyCall.PyObject}:
 PyObject <matplotlib.lines.Line2D object at 0x7f71beacf430>
```

This doesn't:
```julia
julia> using MKL

julia> using PyPlot

julia> plot(3:4)

signal (11): Segmentation fault
in expression starting at none:0
```

This is on
```julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = vim
```
and `MKL v0.4.2`

**Comment by antoine-levitt** [comment]
This looks possibly different, my segfault occurs no matter what order the packages are loaded

**Comment by ViralBShah** [comment]
@staticfloat @giordano Isn't this the usual problem of ILP64 MKL from Julia and LP64 from Python clashing? I believe the next MKL release that allows the `64_` suffixes would solve this.

**Comment by ViralBShah** [comment]
We have worked with Intel MKL team and the fix has landed. This should hopefully give us what we need to fix all these issues. 

https://github.com/JuliaLinearAlgebra/libblastrampoline/issues/52

**Comment by giordano** [comment]
I've been trying to run `using MKL_jll; using PyPlot; plot(3:4)` multiple times, never got a crash.  I wonder if the segfaults have anything to do with `MKL.jl`?  But I think on v1.7 this package doesn't do much apart from forwarding the BLAS calls with lbt?

**Comment by antoine-levitt** [comment]
I can confirm that using MKL_jll (and not using MKL) appears to fix both the MKL+PyPlot as well as the original bug report in this issue.

**Comment by ViralBShah** [comment]
I think if you don't use MKL.jl, we don't initialize MKL or redirect the BLAS symbols in LBT.

**Comment by ViralBShah** [comment]
Progress: https://github.com/JuliaLang/julia/pull/43877

Next step would be to update MKL.jl as discussed in https://github.com/JuliaLinearAlgebra/libblastrampoline/pull/54#issuecomment-1016976960

**Comment by ViralBShah** [comment]
The PyPlot example no longer crashes, irrespective of whether I now load MKL.jl before or after. If #104 is good and merges, this will conclude an extremely long project of working with Intel to bring 64_ suffixes to MKL for ILP64, and then rolling it all out in the Julia ecosystem all the way, enabled by all the work on LBT that @staticfloat and @giordano have done.

**Comment by ViralBShah** [comment]
This also paves the way for us to be able to link Ygg binaries to LBT - both ILP64 and LP64 BLAS - and have the ability to use MKL across the ecosystem.

**Comment by jishnub** [comment]
I seem to still encounter the `PyPlot` crash, am I using the correct version?

```julia
(@v1.8) pkg> st -m MKL
Status `~/.julia/environments/v1.8/Manifest.toml`
  [33e6dc65] MKL v0.4.4 `https://github.com/JuliaLinearAlgebra/MKL.jl#master`

(@v1.8) pkg> st -m PyPlot
Status `~/.julia/environments/v1.8/Manifest.toml`
  [d330b81b] PyPlot v2.10.0

julia> using MKL; using PyPlot; plot(3:4);


signal (11): Segmentation fault
in expression starting at none:0
[1]    29598 segmentation fault (core dumped)  julia-latest
```

**Comment by ViralBShah** [comment]
That's right, #104 fixes it. Would be great if you can try it out. There were a couple of small issues we found that need workarounds (listed in the issue), and after that we can merge it all. Quite hopeful that it will happen by 1.8.

**Comment by jishnub** [comment]
Thanks, I can confirm that the pyplot issue is fixed using that branch. Amazing work! Hoping that this makes it to 1.8

**Comment by ViralBShah** [comment]
We expect it will make it to 1.8.

**Comment by antoine-levitt** [comment]
FWIW, I still get segfaults with julia master and MKL.jl 0.5. Reproducer is the same as the second post above.

**Comment by ViralBShah** [comment]
We haven't been able to merge my PR yet, because Intel gave us ILP64 mangling for fortran names but not CBLAS names, and we need CBLAS for dot. @staticfloat is trying to fix this - but #104 is failing with LBT 5. I hope it will get fixed by the time 1.8 releases. Also, Intel is working on adding CBLAS name mangling for the next release.

**Comment by antoine-levitt** [comment]
@ViralBShah sorry I didn't test at the time of your PR, but the MWE at https://github.com/JuliaLinearAlgebra/MKL.jl/issues/97#issuecomment-992736713 is still failing with julia 1.8.2 and MKL 0.5.0

**Comment by jishnub** [comment]
Could you test against master (MKL 6.0)?

**Comment by antoine-levitt** [comment]
Oh sorry I missed that. Awesome, it works. Can you guys tag a new release?

**Comment by antoine-levitt** [comment]
Bump?

**Comment by ViralBShah** [comment]
What needs to be done here? Didn't 0.6 work?

**Comment by jishnub** [comment]
I think the suggestion is that a release be tagged

**Comment by ViralBShah** [comment]
I thought I tagged v0.6, but Tagbot seems to have errored out and hence no tags or release notes in this repo. See the recent commits.

https://github.com/JuliaRegistries/General/pull/70260
